#pragma once
#pragma pack(push,1)

typedef struct CHARACTER_INFO {
	unsigned long GID;
	int exp;
	int money;
	int jobexp;
	int joblevel;
	int bodystate;
	int healthstate;
	int effectstate;
	int virtue;
	int honor;
	short jobpoint;
	int hp;
	int maxhp;
	short sp;
	short maxsp;
	short speed;
	short job;
	short head;
	short weapon;
	short level;
	short sppoint;
	short accessory;
	short shield;
	short accessory2;
	short accessory3;
	short headpalette;
	short bodypalette;
	unsigned char name[24];
	unsigned char Str;
	unsigned char Agi;
	unsigned char Vit;
	unsigned char Int;
	unsigned char Dex;
	unsigned char Luk;
	unsigned char CharNum;
	unsigned char haircolor;
	short bIsChangedCharName;
	int nRobe;
} CHARACTER_INFO;

typedef struct CHARACTER_INFO_UNION {
	unsigned long GID;
	int exp;
	int money;
	int jobexp;
	int joblevel;
	int bodystate;
	int healthstate;
	int effectstate;
	int virtue;
	int honor;
	short jobpoint;
	int hp;
	int maxhp;
	short sp;
	short maxsp;
	short speed;
	short job;
	short head;
	short weapon;
	short level;
	short sppoint;
	short accessory;
	short shield;
	short accessory2;
	short accessory3;
	short headpalette;
	short bodypalette;
	unsigned char name[24];
	unsigned char Str;
	unsigned char Agi;
	unsigned char Vit;
	unsigned char Int;
	unsigned char Dex;
	unsigned char Luk;
	unsigned char CharNum;
	unsigned char haircolor;
	short bIsChangedCharName;
	int nRobe;
} CHARACTER_INFO_UNION;

typedef struct CHARACTER_INFO_NEO {
	unsigned long GID;
	int exp;
	int money;
	int jobexp;
	int joblevel;
	int bodystate;
	int healthstate;
	int effectstate;
	int virtue;
	int honor;
	short jobpoint;
	int hp;
	int maxhp;
	short sp;
	short maxsp;
	short speed;
	short job;
	short head;
	short weapon;
	short level;
	short sppoint;
	short accessory;
	short shield;
	short accessory2;
	short accessory3;
	short headpalette;
	short bodypalette;
	unsigned char name[24];
	unsigned char Str;
	unsigned char Agi;
	unsigned char Vit;
	unsigned char Int;
	unsigned char Dex;
	unsigned char Luk;
	unsigned char CharNum;
	unsigned char haircolor;
	int nRobe;
} CHARACTER_INFO_NEO;

typedef struct CHARACTER_INFO_NEO_UNION {
	unsigned long GID;
	int exp;
	int money;
	int jobexp;
	int joblevel;
	int bodystate;
	int healthstate;
	int effectstate;
	int virtue;
	int honor;
	short jobpoint;
	int hp;
	int maxhp;
	short sp;
	short maxsp;
	short speed;
	short job;
	short head;
	short weapon;
	short level;
	short sppoint;
	short accessory;
	short shield;
	short accessory2;
	short accessory3;
	short headpalette;
	short bodypalette;
	unsigned char name[24];
	unsigned char Str;
	unsigned char Agi;
	unsigned char Vit;
	unsigned char Int;
	unsigned char Dex;
	unsigned char Luk;
	unsigned char CharNum;
	unsigned char haircolor;
	int nRobe;
	short bIsChangedCharName;
} CHARACTER_INFO_NEO_UNION;


#pragma pack(pop)
